=== sambacha/yearn-registry-list/dev.json
{  "$schema": "http://json-schema.org/draft-04/schema#",
  "name": "Yearn Strategies",
  "logoURI": "https://",
  "keywords": ["audited", "verified", "special strategy" ,"endorsed"],
  "tags": {
    "description": {
      "name": "strategy description",
      "description": "[A-Z,1-9]"
    },
    "strategy": {
      "name": "[A-Z,1-9]",
      "description": "[A-Z,1-9]"
    }
  },
  "timestamp": "2020-06-12T00:00:00+00:00",
  "type": "object",
  "properties": {
    "apiVersion": {
      "type": "string"
    },
    "blockNumber": {
      "type": "string"
    },
    "deploymentId": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "strategies": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
                  "status": { 
                      "type": "string" 
            },
            "blockNumber": {
              "type": "string"
            },
            "debtLimit": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "performanceFee": {
              "type": "string"
            },
            "rateLimit": {
              "type": "string"
            },
            "strategy": {
              "type": "string"
            },
            "timestamp": {
              "type": "string"
            },
            "vault": {
              "type": "string"
            }
          },
          "required": [
              "status",
            "blockNumber",
            "debtLimit",
            "id",
            "performanceFee",
            "rateLimit",
            "strategy",
            "timestamp",
            "vault"
          ]
        }
      ]
    },
    "timestamp": {
      "type": "string"
    },
    "token": {
      "type": "string"
    },
    "tokenDecimals": {
      "type": "string"
    },
    "tokenName": {
      "type": "string"
    },
    "tokenSymbol": {
      "type": "string"
    },
    "transaction": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    },
    "vault": {
      "type": "string"
    },
    "vaultDecimals": {
      "type": "string"
    },
    "vaultName": {
      "type": "string"
    },
    "vaultSymbol": {
      "type": "string"
    }
  },
  "required": [
    "apiVersion",
    "blockNumber",
    "deploymentId",
    "id",
    "status",
    "strategies",
    "timestamp",
    "token",
    "tokenDecimals",
    "tokenName",
    "tokenSymbol",
    "transaction",
    "vault",
    "vaultDecimals",
    "vaultName",
    "vaultSymbol"
  ],
  
  "strategy": [
    {
      "chainId": 1,
      "deploymentId": "0x",
      "symbol": "[A-Z,1-9]",
      "name": "[A-Z,1-9]",
      "decimals": 6,
      "logoURI": "ipfs://",
      "tags": ["[A-Z,1-9]"]
    }
  ],
  "version": {
    "major": 0,
    "minor": 3,
    "patch": 0
  }
}

=== sambacha/yearn-registry-list/vault_example.json
[
  {
    "apiVersion": "0.2.2",
    "blockNumber": "7662721",
    "deploymentId": "0",
    "id": "0x03c78f5af012e0eef74dc0a7d3fee4f728a4ffa6",
    "status": "Endorsed",
    "strategies": [
      {
        "blockNumber": "7662768",
        "debtLimit": "0",
        "id": "0x0835c3993ad6e2f1731da4782c3add6dfbf0abf0",
        "performanceFee": "0",
        "rateLimit": "0",
        "strategy": "0x0835c3993ad6e2f1731da4782c3add6dfbf0abf0",
        "timestamp": "1607114109000",
        "vault": "0x03c78f5af012e0eef74dc0a7d3fee4f728a4ffa6"
      }
    ],
    "timestamp": "1607113404000",
    "token": "0xdf032bc4b9dc2782bb09352007d4c57b75160b15",
    "tokenDecimals": "18",
    "tokenName": "Wrapped Ether",
    "tokenSymbol": "WETH",
    "transaction": {
      "id": "0xa9719441a00d1de9142c26fc1842059eb5d93b19352b9c7c88b2273da29bc7ac-71"
    },
    "vault": "0x03c78f5af012e0eef74dc0a7d3fee4f728a4ffa6",
    "vaultDecimals": "18",
    "vaultName": "Yearn Wrapped Ether Vault",
    "vaultSymbol": "yvWETH"
  },
  {
    "apiVersion": "0.3.0",
    "blockNumber": "7662795",
    "deploymentId": "1",
    "id": "0x81f69866e3838a26fdcab3f22efc1bdb549cebad",
    "status": "Endorsed",
    "strategies": [],
    "timestamp": "1607114514000",
    "token": "0x31958e219073d60fdceb1d608c293754331dd352",
    "tokenDecimals": "18",
    "tokenName": "Graph Token",
    "tokenSymbol": "GRT",
    "transaction": {
      "id": "0x23c8ce272b312501d4dd7cfcc2fe883e719b55ed8d7adb2b26b303f856e77011-15"
    },
    "vault": "0x81f69866e3838a26fdcab3f22efc1bdb549cebad",
    "vaultDecimals": "18",
    "vaultName": "Yearn Graph Token Vault",
    "vaultSymbol": "yvGRT"
  },
  {
    "apiVersion": "0.3.0",
    "blockNumber": "7662813",
    "deploymentId": "-1",
    "id": "0x8760494cc554672a1c75f606f5865d230561f22a",
    "status": "Experimental",
    "strategies": [],
    "timestamp": "1607114784000",
    "token": "0xdf032bc4b9dc2782bb09352007d4c57b75160b15",
    "tokenDecimals": "18",
    "tokenName": "Wrapped Ether",
    "tokenSymbol": "WETH",
    "transaction": {
      "id": "0x625b353ebc6b5cac38147ab692cf62313bd3a28e4c3f4997b7a863ef8ee3ec2f-5"
    },
    "vault": "0x8760494cc554672a1c75f606f5865d230561f22a",
    "vaultDecimals": "18",
    "vaultName": "Yearn Wrapped Ether Vault",
    "vaultSymbol": "yvWETH"
  },
  {
    "apiVersion": "0.2.2",
    "blockNumber": "7662716",
    "deploymentId": "0",
    "id": "0xa914731d91c61af260bc479779ae24008ccecc8c",
    "status": "Endorsed",
    "strategies": [
      {
        "blockNumber": "7662755",
        "debtLimit": "0",
        "id": "0x0579fc0e764e7cc10c7175533b1330b184b8d505",
        "performanceFee": "0",
        "rateLimit": "0",
        "strategy": "0x0579fc0e764e7cc10c7175533b1330b184b8d505",
        "timestamp": "1607113914000",
        "vault": "0xa914731d91c61af260bc479779ae24008ccecc8c"
      },
      {
        "blockNumber": "7662753",
        "debtLimit": "0",
        "id": "0xcfa445f5d5d00b226bcc543fe24cfd40b88450eb",
        "performanceFee": "0",
        "rateLimit": "0",
        "strategy": "0xcfa445f5d5d00b226bcc543fe24cfd40b88450eb",
        "timestamp": "1607113884000",
        "vault": "0xa914731d91c61af260bc479779ae24008ccecc8c"
      },
      {
        "blockNumber": "7662757",
        "debtLimit": "0",
        "id": "0xfd35639c74bb7f3144a6cf43de896094a932427f",
        "performanceFee": "0",
        "rateLimit": "0",
        "strategy": "0xfd35639c74bb7f3144a6cf43de896094a932427f",
        "timestamp": "1607113944000",
        "vault": "0xa914731d91c61af260bc479779ae24008ccecc8c"
      }
    ],
    "timestamp": "1607113329000",
    "token": "0x31958e219073d60fdceb1d608c293754331dd352",
    "tokenDecimals": "18",
    "tokenName": "Graph Token",
    "tokenSymbol": "GRT",
    "transaction": {
      "id": "0x4437affe01e7121f5123d7ae17eee29494fbf58068c8b059849e99b35ce79a2a-126"
    },
    "vault": "0xa914731d91c61af260bc479779ae24008ccecc8c",
    "vaultDecimals": "18",
    "vaultName": "Yearn Graph Token Vault",
    "vaultSymbol": "yvGRT"
  },
  {
    "apiVersion": "0.3.0",
    "blockNumber": "7662889",
    "deploymentId": "0",
    "id": "0xe1793a354db941a6d5f70f3cbede9bbfff66a3cb",
    "status": "Endorsed",
    "strategies": [],
    "timestamp": "1607115924000",
    "token": "0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea",
    "tokenDecimals": "18",
    "tokenName": "Dai",
    "tokenSymbol": "DAI",
    "transaction": {
      "id": "0x63fa40d9f6ba88cdbe086feff87c21b65f000698ea10e01426cfffeaa6ab6e57-36"
    },
    "vault": "0xe1793a354db941a6d5f70f3cbede9bbfff66a3cb",
    "vaultDecimals": "18",
    "vaultName": "Yearn Dai Vault",
    "vaultSymbol": "yvDAI"
  }
]

=== sambacha/yearn-registry-list/test.vault.json
{
    "apiVersion": "0.2.2",
    "blockNumber": "7662721",
    "deploymentId": "0",
    "id": "0x03c78f5af012e0eef74dc0a7d3fee4f728a4ffa6",
    "status": "Endorsed",
    "strategies": [
      {
        "blockNumber": "7662768",
        "debtLimit": "0",
        "id": "0x0835c3993ad6e2f1731da4782c3add6dfbf0abf0",
        "performanceFee": "0",
        "rateLimit": "0",
        "strategy": "0x0835c3993ad6e2f1731da4782c3add6dfbf0abf0",
        "timestamp": "1607114109000",
        "vault": "0x03c78f5af012e0eef74dc0a7d3fee4f728a4ffa6"
      }
    ],
    "timestamp": "1607113404000",
    "token": "0xdf032bc4b9dc2782bb09352007d4c57b75160b15",
    "tokenDecimals": "18",
    "tokenName": "Wrapped Ether",
    "tokenSymbol": "WETH",
    "transaction": {
      "id": "0xa9719441a00d1de9142c26fc1842059eb5d93b19352b9c7c88b2273da29bc7ac-71"
    },
    "vault": "0x03c78f5af012e0eef74dc0a7d3fee4f728a4ffa6",
    "vaultDecimals": "18",
    "vaultName": "Yearn Wrapped Ether Vault",
    "vaultSymbol": "yvWETH"
}
